In [ ]:
#importing the Python Library
import numpy as np

In [ ]:
my_list=[1,2,3]
x=np.array(my_list)
x

array([1, 2, 3])

In [ ]:
y=np.array([4,5,6])
y

array([4, 5, 6])

In [ ]:
m=np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#we will get the shape of variable m
m.shape

(2, 3)

In [ ]:
#we well get the size of varible m
m.size

6

In [ ]:
#Creating a range from 0 to 30 
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
#Reshaping the value of n
n=n.reshape(3,5)
n


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
#we will get the Size of n 
n.size

15

In [ ]:
#using Linespace operation
o=np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
#using Shape operation it will show how many rows and colums are there
o.shape

(9,)

In [ ]:
#reshape the values
o.reshape(3,3)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#we will get diagnol value of y
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [ ]:
np.array([1,2,3]*4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
p=np.ones([2,3],int) #intiger values well be print if not mentioned int, Float values will be print 
p

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#vertival Stack
np.vstack([p,2*p])


array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
#Horizontal Stack
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [ ]:
#0 Dimension Tensor
x=np.array(12)
print(x.ndim)

0


In [ ]:
#1 Dimension Tensor
y=np.array([200,300,400])
print(y.ndim)

1


In [ ]:
# 2 Dimension Tensor
z=np.array([[5,78,2,34,0],
            [45,67,23,90,45],
            [65,7,89,34,78]])

print(z.ndim)

2
